services:
  nano.template.console:
    image: nano.template.console
    restart: on-failure
    build:
      context: .
      dockerfile: ../Nano.Template.Console/Dockerfile
    # depends_on:
    #   - database
    #   - eventing
    networks:
      - network

  # database:
  #   image: mysql/mysql-server:latest
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - network
  #   environment:
  #     MYSQL_USER: "sa"
  #     MYSQL_PASSWORD: "myPassword_123"
  #     MYSQL_ROOT_PASSWORD: "myPassword_123"
  #     MYSQL_DATABASE: "webDb" 

  # eventing: 
  #   image: rabbitmq:management
  #   ports:
  #     - 5671:5671
  #     - 5672:5672
  #     - 15671:15671
  #     - 15672:15672
  #   environment: 
  #     RABBITMQ_DEFAULT_USER: "myUser"
  #     RABBITMQ_DEFAULT_PASS: "myPassword"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   networks:
  #     - network

networks:
  network:
    name: network
    external: true
