services:
  database:
    environment:
      SA_PASSWORD: "myPassword_123"
      ACCEPT_EULA: "Y"  

#  database:
#    environment:
#      MYSQL_USER: "sa"
#      MYSQL_PASSWORD: "myPassword_123"
#      MYSQL_ROOT_PASSWORD: "myPassword_123"
#      MYSQL_DATABASE: "webDb"
  
  eventing: 
    environment: 
      RABBITMQ_DEFAULT_USER: "myUser"
      RABBITMQ_DEFAULT_PASS: "myPassword"
      RABBITMQ_DEFAULT_VHOST: "/"
