version: '3.7'

services:
  nano.template.console:
    image: nano.template.console
    restart: on-failure
    build:
      context: .
      dockerfile: ../Nano.Template.Console/Dockerfile
    depends_on:
      - database
      - eventing
    networks:
      - network

  database:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    networks:
      - network

#  database:
#    image: mysql/mysql-server:5.7
#    ports:
#      - 3306:3306
#    networks:
#      - network

  eventing: 
    image: rabbitmq:3.7.5
    ports:
      - 5671:5671
      - 5672:5672
    networks:
      - network

networks:
  network:
    name: network
