version: '3.7'

services:
  nano.template.console:
    image: nano.template.console
    restart: on-failure
    build:
      context: .
      dockerfile: ../Nano.Template.Console/Dockerfile
    networks:
      - network

networks:
  network:
    external: true