services:
  api.public:
    image: api.public
    hostname: api-public
    restart: on-failure
    ports:
      - 8080:8080
      - 4443:4443
    build:
      context: ../Api.Public
      dockerfile: "Dockerfile.Local"
    depends_on:
      - clamav
      - svc.accounts
      - svc.places
      - svc.locations
      - svc.emailing
    volumes:
      - ../:/root/.dotnet/https
    networks:
      - network

  clamav: 
    image: clamav/clamav
    hostname: clamav
    ports:
      - 3310:3310
    networks:
      - network

  svc.accounts:
    image: svc-accounts
    hostname: svc-accounts
    restart: on-failure
    ports:
      - 8181:8080
    build:
      context: ../../Svc.Accounts/Svc.Accounts
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/aspnet:10.0

        RUN apt-get update && apt-get install -y \
            libfontconfig1 \
            libfreetype6 \
            && rm -rf /var/lib/apt/lists/*

        WORKDIR /app
        COPY ./bin/publish/. .
        ENTRYPOINT ["dotnet", "Svc.Accounts.dll"]
    environment:
      ASPNETCORE_HTTP_PORTS: ""
    depends_on:
      - database
      - eventing
    networks:
      - network
    volumes:
      - ./bin/svc-accounts:/mnt/svc-accounts

  svc.places:
    image: svc-places
    hostname: svc-places
    restart: on-failure
    ports:
      - 8282:8080
    build:
      context: ../../Svc.Places/Svc.Places
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/aspnet:10.0

        RUN apt-get update && apt-get install -y \
            libfontconfig1 \
            libfreetype6 \
            && rm -rf /var/lib/apt/lists/*

        WORKDIR /app
        COPY ./bin/publish/. .
        ENTRYPOINT ["dotnet", "Svc.Places.dll"]
    environment:
      ASPNETCORE_HTTP_PORTS: ""
    depends_on:
      - database
      - eventing
    networks:
      - network
    volumes:
      - ./bin/svc-places:/mnt/svc-places

  svc.locations:
    image: svc-locations
    hostname: svc-locations
    restart: on-failure
    ports:
      - 8383:8080
    build:
      context: ../../Svc.Locations/Svc.Locations
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/aspnet:10.0
        WORKDIR /app
        COPY ./bin/publish/. .
        ENTRYPOINT ["dotnet", "Svc.Locations.dll"]
    environment:
      ASPNETCORE_HTTP_PORTS: ""
    depends_on:
      - database
      - eventing
    networks:
      - network

  svc.emailing:
    image: svc-emailing
    hostname: svc-emailing
    restart: on-failure
    ports:
      - 8484:8080
    build:
      context: ../../Svc.Emailing/Svc.Emailing
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/aspnet:10.0
        WORKDIR /app
        COPY ./bin/publish/. .
        ENTRYPOINT ["dotnet", "Svc.Emailing.dll"]
    environment:
      ASPNETCORE_HTTP_PORTS: ""
      Emailing__ApiKey: "<<secret>>"
    depends_on:
      - database
      - eventing
    networks:
      - network

  database:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    networks:
      - network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: myPassword_123

  eventing: 
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    networks:
      - network
    environment: 
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /

networks:
  network:
    name: network
    driver: bridge
