<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Authors>Michael Vivet</Authors>
		<Product>Nano.Template.Service.Models</Product>
		<Description>Models for Nano web template.</Description>
		<Copyright></Copyright>
		<PackageProjectUrl>https://github.com/vivet/Nano.Templates</PackageProjectUrl>
		<RepositoryUrl>https://github.com/vivet/Nano.Templates.git</RepositoryUrl>
		<PackageTags>nano template web models</PackageTags>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Nano.Template.Service.Models</PackageId>
		<Version>1.0.0.0</Version>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RepositoryType>git</RepositoryType>
		<NeutralLanguage>en-US</NeutralLanguage>
		<WarningsAsErrors />
		<NoWarn>NU1902, NU5104</NoWarn>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<DocumentationFile>$(MSBuildThisFileDirectory)\bin\$(Configuration)\Nano.Template.Service.Models.xml</DocumentationFile>
  	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.App.Api\Nano.App.Api.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.App\Nano.App.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Common\Nano.Common.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Data.Abstractions\Nano.Data.Abstractions.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Data.InMemory\Nano.Data.InMemory.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Data.MySql\Nano.Data.MySql.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Data.SqLite\Nano.Data.SqLite.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Data.SqlServer\Nano.Data.SqlServer.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Data\Nano.Data.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Eventing.Abstractions\Nano.Eventing.Abstractions.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Eventing.RabbitMq\Nano.Eventing.RabbitMq.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Eventing\Nano.Eventing.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Logging.Abstractions\Nano.Logging.Abstractions.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Logging.Log4Net\Nano.Logging.Log4Net.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Logging.Microsoft\Nano.Logging.Microsoft.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Logging.NLog\Nano.Logging.NLog.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Logging.Serilog\Nano.Logging.Serilog.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Logging\Nano.Logging.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Storage.Abstractions\Nano.Storage.Abstractions.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Storage.AzureShare\Nano.Storage.AzureShare.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Storage.LocalShare\Nano.Storage.LocalShare.csproj" />
	  <ProjectReference Include="..\..\..\Nano.Library\Nano.Storage\Nano.Storage.csproj" />
	</ItemGroup>

</Project>