apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: %SERVICE_NAME%
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  successfulJobsHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  jobTemplate:
    metadata:
      labels:
        app: %SERVICE_NAME%
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 2000 
          containers:
          - name: %SERVICE_NAME%
            image: %DOCKER_REGISTRY%/%APP_NAME%:%APP_VERSION%
            imagePullPolicy: Always 
            envFrom:
            - configMapRef:
                name: %SERVICE_NAME%-config
            resources:
              requests:
                memory: %KUBERNETES_MEMORY_REQUEST%
                cpu: %KUBERNETES_CPU_REQUEST%
              limits:
                memory: %KUBERNETES_MEMORY_LIMIT%
                cpu: %KUBERNETES_CPU_LIMIT%
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 2000
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          restartPolicy: OnFailure
          volumes:
          - name: tmp
            emptyDir: {}
          imagePullSecrets:
          - name: docker-registry-secret


