apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: %SERVICE_NAME%
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  successfulJobsHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  jobTemplate:
    metadata:
      labels:
        app: %SERVICE_NAME%
    spec:
      template:
        spec:
          containers:
          - name: %SERVICE_NAME%
            image: %DOCKER_REGISTRY%/%APP_NAME%:%APP_VERSION%
            imagePullPolicy: Always 
            envFrom:
            - configMapRef:
                name: %SERVICE_NAME%-config
            resources:
              requests:
                memory: %KUBERNETES_MEMORY_REQUEST%
                cpu: %KUBERNETES_CPU_REQUEST%
              limits:
                memory: %KUBERNETES_MEMORY_LIMIT%
                cpu: %KUBERNETES_CPU_LIMIT%
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-registry-secret
