name: Build And Deploy
on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 
  workflow_dispatch:
env:
  APP_NAME: Cmd.SignUps
  IMAGE_NAME: cmd.signups
  SERVICE_NAME: cmd-signups
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  DOTNET_SDK_VERSION: "10.0"
  DOTNET_ASPNET_VERSION: "10.0"
  AZURE_GROUP_KUBERNETES: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES }}
  AZURE_GROUP_DELIVERY: ${{ vars.AZURE_RESOURCE_GROUP_DELIVERY }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  NUGET_HOST: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  NUGET_USERNAME: ${{ github.actor }}
  NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  KUBERNETES_NODEPOOL_COMPUTE: cpu
  KUBERNETES_NAMESPACE: ${{ vars.KUBERNETES_NAMESPACE }}
  KUBERNETES_REPLICA_HISTORY_COUNT: 4
  KUBERNETES_MEMORY_REQUEST: 256Mi
  KUBERNETES_MEMORY_LIMIT: 768Mi
  KUBERNETES_CPU_REQUEST: 50m
  KUBERNETES_CPU_LIMIT: 150m
  KUBERNETES_CRONJOB_SCHEDULE: "0 */2 * * *"
  DOTNET_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - linux 
      - ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}
    permissions:
      packages: read
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        shell: pwsh
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;

          $env:KUBERNETES_CLUSTER = az aks list -g $env:AZURE_GROUP_KUBERNETES --query [0].name -o tsv;
          az aks get-credentials -g $env:AZURE_GROUP_KUBERNETES -n $env:KUBERNETES_CLUSTER --overwrite -o none;

      - name: Build Solution
        shell: pwsh
        run: |
          dotnet nuget add source $env:NUGET_HOST -n private -u $env:NUGET_USERNAME -p $env:NUGET_PASSWORD --store-password-in-clear-text;

          dotnet build -c Release .\$env:APP_NAME.sln;

          if ($LastExitCode -ne 0)
          { 
              throw "error";
          };

      - name: Test Solution
        shell: pwsh
        run: |
          dotnet test .\.tests\Tests.$env:APP_NAME\Tests.$env:APP_NAME.csproj;

          if ($LastExitCode -ne 0)
          { 
            throw "error";
          };

      - name: Build & Push Image
        shell: pwsh
        run: |
          $env:CONTAINER_REGISTRY_HOST = az acr list -g $env:AZURE_GROUP_DELIVERY --query [0].loginServer -o tsv;

          az acr build `
              --registry $env:CONTAINER_REGISTRY_HOST `
              --agent-pool buildpool `
              -t "$($env:IMAGE_NAME):latest" `
              -t "$($env:IMAGE_NAME):$($env:VERSION)" `
              --build-arg DOTNET_SDK_VERSION=$env:DOTNET_SDK_VERSION `
              --build-arg DOTNET_ASPNET_VERSION=$env:DOTNET_ASPNET_VERSION `
              --build-arg CONTAINER_REGISTRY_SOURCE_LABEL=https://github.com/$env:GITHUB_REPOSITORY `
              --build-arg NUGET_HOST=$env:NUGET_HOST `
              --build-arg NUGET_USERNAME=$env:NUGET_USERNAME `
              --build-arg NUGET_PASSWORD=$env:NUGET_PASSWORD `
              ./

          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          };  

          echo "CONTAINER_REGISTRY_HOST=$env:CONTAINER_REGISTRY_HOST" >> $env:GITHUB_ENV;

      - name: Kubernetes Deploy
        shell: pwsh
        run: |
          Get-Content .kubernetes/configmap.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/configmap.tmp.yaml;
          kubectl apply -f .kubernetes/configmap.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          };  

          Get-Content .kubernetes/cronjob.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/cronjob.tmp.yaml;
          kubectl apply -f .kubernetes/cronjob.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          };  

      - name: GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
            Build run: ${{ github.run_number }}
            Image: ${{ env.CONTAINER_REGISTRY_HOST }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          artifacts: "nupkgs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
