<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<NoWarn />
		<AssemblyVersion>10.0.0.0</AssemblyVersion>
		<FileVersion>10.0.0.0</FileVersion>
		<Version>10.0.0.0</Version>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Configurations>Debug;Release</Configurations>
		<LangVersion>latest</LangVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<nullable>enable</nullable>
		<License>LICENSE</License>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IsPackable>false</IsPackable>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='RELEASE'">
		<Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="NanoCore" Version="10.0.4" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Svc.Accounts\Svc.Accounts.Models\Svc.Accounts.Models.csproj" />
	</ItemGroup>

</Project>