services:
  nano.template.api:
    image: nano.template.api
    build:
      context: .
      dockerfile: ../Nano.Template.Api/Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    #depends_on:
      #- clamav
      #- nano.template.web
    networks:
      - network
    volumes:
      - ../:/root/.dotnet/https

  # clamav: 
  #   image: clamav/clamav
  #   hostname: clamav
  #   ports:
  #     - 3310:3310
  #   networks:
  #     - network
      
  # nano.template.web:
  #   image: nano.template.web:dev
  #   hostname: nano-template-web
  #   # build:
  #   #   context: ../Web
  #   #   dockerfile: ../../Web/Nano.Template.Web/Dockerfile
  #   ports:
  #     - 8080:8080
  #     - 4443:4443
  #   depends_on:
  #     - database
  #     - eventing
  #   env_file:
  #     - .env
  #   networks:
  #     - network

networks:
  network:
    name: network
