apiVersion: v1
kind: ConfigMap
metadata:
  name: %SERVICE_NAME%-config
  namespace: %KUBERNETES_NAMESPACE%
data:
  ASPNETCORE_ENVIRONMENT: %ENVIRONMENT%
  App__Version: %APP_VERSION%
  Security__Jwt__Issuer: %ENVIRONMENT%.nano
  Security__Jwt__Audience: %ENVIRONMENT%.nano
  Security__Jwt__SecretKey: %NANO_AUTH_JWT_SECRET_KEY%
  Security__User__AdminPassword: %NANO_AUTH_ADMIN_PASSWORD%
  Data__ConnectionString: %DATA_CONNECTIONSTRING%
  Eventing__Username: %EVENTING_USERNAME%
  Eventing__Password: %EVENTING_PASSWORD%
