apiVersion: apps/v1
kind: Deployment
metadata:
  name: %SERVICE_NAME%
  namespace: %KUBERNETES_NAMESPACE%
  labels:
    app: %SERVICE_NAME%
spec:
  replicas: %KUBERNETES_REPLICA_COUNT%
  revisionHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  selector:
    matchLabels:
      app: %SERVICE_NAME%
  template:
    metadata:
      labels:
        app: %SERVICE_NAME%
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000 
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: %SERVICE_NAME%  
      automountServiceAccountToken: false
      containers:
      - name: %SERVICE_NAME%
        image: %AZURE_ACR_HOST%/%APP_NAME%:%VERSION%
        ports:
        - containerPort: 8080
        - containerPort: 4443
        imagePullPolicy: Always 
        env:
        - name: Eventing__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: Security__Jwt__PublicKey
          valueFrom:
            secretKeyRef:
              name: auth-jwt-keys-secret
              key: jwt-public-key
        - name: Security__Jwt__PrivateKey
          valueFrom:
            secretKeyRef:
              name: auth-jwt-keys-secret
              key: jwt-private-key
        envFrom:
        - configMapRef:
            name: %SERVICE_NAME%-config
        resources:
          requests:
            memory: %KUBERNETES_MEMORY_REQUEST%
            cpu: %KUBERNETES_CPU_REQUEST%
          limits:
            memory: %KUBERNETES_MEMORY_LIMIT%
            cpu: %KUBERNETES_CPU_LIMIT%
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          initialDelaySeconds: 10
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: %SERVICE_NAME%-volume
          mountPath: /mnt/%STORAGE_SHARE_NAME%
      volumes:
      - name: tmp
        emptyDir: {}
      - name: %SERVICE_NAME%-volume
        azureFile:
          secretName: storage-account-secret
          shareName: %STORAGE_SHARE_NAME%
          readOnly: false
      imagePullSecrets:
      - name: docker-registry-secret
