apiVersion: v1
kind: Service
metadata:
  name: %SERVICE_NAME%
  namespace: %KUBERNETES_NAMESPACE%
spec:
  ports:  
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: %SERVICE_NAME%
  type: ClusterIP
