version: '3.4'

services:
  nano.basic:
    image: nano.basic
    build:
      context: .
      dockerfile: Nano.Basic/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql/mysql-server
    ports:
      - 3306:3306

  rabbitmq: 
    image: rabbitmq:alpine
    ports:
      - 5671:5671
      - 5672:5672