<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<LangVersion>latest</LangVersion>
		<NoWarn>NU1902</NoWarn>
		<WarningsAsErrors />
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
		<PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Nano.Template.Service\Nano.Template.Service.csproj" />
		<ProjectReference Include="..\..\Nano.Template.Service.Models\Nano.Template.Service.Models.csproj" />
	</ItemGroup>

</Project>
