apiVersion: v1
kind: ConfigMap
metadata:
  name: %SERVICE_NAME%-config
  namespace: %KUBERNETES_NAMESPACE%
data:
  App__Version: %APP_VERSION%
  ASPNETCORE_ENVIRONMENT: %ENVIRONMENT%
  Security__Jwt__Issuer: %ENVIRONMENT%.nano
  Security__Jwt__Audience: %ENVIRONMENT%.nano
  Security__Jwt__SecretKey: %NANO_AUTH_JWT_SECRET_KEY%
