apiVersion: v1
kind: ConfigMap
metadata:
  name: %SERVICE_NAME%-config
  namespace: %KUBERNETES_NAMESPACE%
data:
  App__Version: %VERSION%
  ASPNETCORE_ENVIRONMENT: %ENVIRONMENT%
  #Monitoring__ConnectionString: %APPLICATION_INSIGHT_CONNECTIONSTRING%

