apiVersion: apps/v1
kind: Deployment
metadata:
  name: %SERVICE_NAME%
  namespace: %KUBERNETES_NAMESPACE%
  labels:
    app: %SERVICE_NAME%
spec:
  replicas: %KUBERNETES_REPLICA_COUNT%
  revisionHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  selector:
    matchLabels:
      app: %SERVICE_NAME%
  template:
    metadata:
      labels:
        app: %SERVICE_NAME%
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000 
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              name: %SERVICE_NAME%  
      automountServiceAccountToken: false
      containers:
      - name: %SERVICE_NAME%
        image: %AZURE_ACR_HOST%/%APP_NAME%:%VERSION%
        ports:
        - containerPort: 8080
        - containerPort: 4443
        imagePullPolicy: Always 
        env:
        - name: Security__Jwt__PublicKey
          valueFrom:
            secretKeyRef:
              name: auth-jwt-keys-secret
              key: jwt-public-key
        envFrom:
        - configMapRef:
            name: %SERVICE_NAME%-config
        resources:
          requests:
            memory: %KUBERNETES_MEMORY_REQUEST%
            cpu: %KUBERNETES_CPU_REQUEST%
          limits:
            memory: %KUBERNETES_MEMORY_LIMIT%
            cpu: %KUBERNETES_CPU_LIMIT%
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          periodSeconds: 20
          initialDelaySeconds: 15
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          periodSeconds: 5
          initialDelaySeconds: 10
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: docker-registry-secret