apiVersion: apps/v1
kind: Deployment
metadata:
  name: %SERVICE_NAME%
  namespace: %KUBERNETES_NAMESPACE%
  labels:
    app: %SERVICE_NAME%
spec:
  replicas: %KUBERNETES_REPLICA_COUNT%
  revisionHistoryLimit: %KUBERNETES_REPLICA_HISTORY_COUNT%
  selector:
    matchLabels:
      app: %SERVICE_NAME%
  template:
    metadata:
      labels:
        app: %SERVICE_NAME%
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000 
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: %SERVICE_NAME%  
      automountServiceAccountToken: false
      nodeSelector:
        nodepool.compute: %KUBERNETES_NODEPOOL_COMPUTE%
        kubernetes.io/os: linux
      containers:
      - name: %SERVICE_NAME%
        image: %CONTAINER_REGISTRY_HOST%/%IMAGE_NAME%:%VERSION%
        ports:
        - containerPort: 8080
        - containerPort: 4443
        imagePullPolicy: Always 
        env:
        - name: Security__Jwt__PublicKey
          valueFrom:
            secretKeyRef:
              name: auth-jwt-keys-secret
              key: jwt-public-key
        - name: Sms__ApiKey
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: apikey
        - name: Sms__SenderPhoneNumber
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: sender
        - name: Emailing__ApiKey
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: apikey
        - name: Emailing__SenderName
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: sender-name
        - name: Emailing__SenderEmailAddress
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: sender-email
        envFrom:
        - configMapRef:
            name: %SERVICE_NAME%-config
        resources:
          requests:
            memory: %KUBERNETES_MEMORY_REQUEST%
            cpu: %KUBERNETES_CPU_REQUEST%
          limits:
            memory: %KUBERNETES_MEMORY_LIMIT%
            cpu: %KUBERNETES_CPU_LIMIT%
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          initialDelaySeconds: 30
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          initialDelaySeconds: 20
          timeoutSeconds: 2
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
        - name: ghcr-pull-secret
