apiVersion: v1
kind: Service
metadata:
  name: %SERVICE_NAME%
  namespace: %KUBERNETES_NAMESPACE%
spec:
  ports:
  - name: http
    port: 8080
  - name: https
    port: 4443
  selector:
    app: %SERVICE_NAME%
  type: ClusterIP
