<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<NoWarn />
		<Authors>Michael Vivet</Authors>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Version>1.0.0</Version>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Configurations>Debug;Release</Configurations>
		<LangVersion>latest</LangVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<nullable>enable</nullable>
		<License>LICENSE</License>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IsPackable>true</IsPackable>
		<Authors>Michael Vivet</Authors>
		<Owners>Michael Vivet</Owners>
		<Product>$(ProjectName)</Product>
		<Summary>Example project demonstrating a focused aspect of the Nano Library.</Summary>
		<Description>Image handling implementation.</Description>
		<PackageReleaseNotes></PackageReleaseNotes>
		<RepositoryType>git</RepositoryType>
		<RepositoryBranch>main</RepositoryBranch>
		<RepositoryUrl>https://github.com/Nano-Core/Nano.Templates.git</RepositoryUrl>
		<RepositoryCommit>$(GitCommitHash)</RepositoryCommit>
		<EmbedAllSources>true</EmbedAllSources>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageVersion>$(Version)</PackageVersion>
		<PackageTags>image</PackageTags>
		<PackageProjectUrl>https://github.com/Nano-Core/Nano.Templates/$(ProjectName)</PackageProjectUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SkiaSharp" Version="4.150.0" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.0" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)'=='RELEASE'">
		<Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE" Pack="true" Visible="false" PackagePath="" />
		<None Include="..\icon.png" Pack="true" Visible="false" PackagePath="" />
		<None Include="..\README.md" Pack="true" Visible="false" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.103" PrivateAssets="All" />
	</ItemGroup>

</Project>