apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: %SERVICE_NAME%-monitor
  namespace: %KUBERNETES_NAMESPACE%
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: %SERVICE_NAME%
  endpoints:
    - port: http
      path: /metrics
      interval: 1m