apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-secret
  namespace: %KUBERNETES_NAMESPACE%
type: Opaque
stringData:
  jwt-public-key: %AUTH_JWT_PUBLIC_KEY%
  jwt-private-key: %AUTH_JWT_PRIVATE_KEY%

