name: Build and Deploy
on:
  pull_request:
    branches:
      - master 
  push:
    branches:
      - master 
env:
  VERSION: 10.0.0-rc1
jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6

      - name: GitHub Release
        if: github.ref == 'refs/heads/master' 
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}.${{ github.run_number }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ contains(env.VERSION, '-') }}